//CONSTANTS HERE FOR ACTION TYPES

const LOADING_USER = "LOADING_USER"
const FETCHED_USER = "FETCHED_USER"
const AUTHENTICATED_USER = "AUTHENTICATED_USER"
const CREATING_USER = "CREATING_USER"
const EDIT_USER = "EDIT_USER"

export { EDIT_USER, CREATING_USER, LOADING_USER, FETCHED_USER, AUTHENTICATED_USER}
