//CONSTANTS HERE FOR ACTION TYPES

const LOADING_USER = "LOADING_USER"
const FETCHED_USER = "FETCHED_USER"
const AUTHENTICATED_USER = "AUTHENTICATED_USER"
const CREATING_USER = "CREATING_USER"
const EDIT_USER = "EDIT_USER"
const FETCHED_PROJECT = "FETCHED_PROJECT"
const PATCH_PROJECT = "PATCH_PROJECT"
const FETCHED_TARGET_USER = "FETCHED_TARGET_USER"
const LOGOUT_USER = "LOGOUT_USER"
const UNAUTHENTICATE_USER = "UNAUTHENTICATE_USER"
const FETCHED_BOUNTY = "FETCHED_BOUNTY"

export { FETCHED_BOUNTY, LOGOUT_USER, UNAUTHENTICATE_USER, FETCHED_TARGET_USER, PATCH_PROJECT, FETCHED_PROJECT, EDIT_USER, CREATING_USER, LOADING_USER, FETCHED_USER, AUTHENTICATED_USER}
