//CONSTANTS HERE FOR ACTION TYPES

const LOADING_USER = "LOADING_USER"
const FETCHED_USER = "FETCHED_USER"
const AUTHENTICATED_USER = "AUTHENTICATED_USER"

export {LOADING_USER, FETCHED_USER, AUTHENTICATED_USER}
